GET http://localhost:8080/pinboard

###

GET http://localhost:8080/pinboard/1

###

POST http://localhost:8080/pinboard/1/note
Content-Type: application/json

{
  "headline": "First Note",
  "text": "This is a simple Note",
  "posX": 10,
  "posY": 10,
  "priority": 1
}

###

GET http://localhost:8080/pinboard/1/notes

###

DELETE http://localhost:8080/pinboard/1/deleteNote/1

###

DELETE http://localhost:8080/pinboard/1

###
