###

POST http://localhost:8080/user
Content-Type: application/json

{
  "uid": "XNVU0NfasfW6Iyehn5nXixODyHI2",
  "email": "simon.ittensammer@gmail.com",
  "photoURL": "https://lh3.googleusercontent.com/a-/AOh14GjiF9Gc1oGk3K13IVEdMvmYGBzChmX4t3ayGvYkgg=s96-c",
  "displayName": "Simon Itti"
}

###

GET http://localhost:8080/user
Accept: application/json

###
