###

#POST http://localhost:8080/user
#Content-Type: application/json
#
#{
#  "uid": "XNVU0NfasfW6Iyehn5nXixODyHI2",
#  "email": "simon.ittensammer@gmail.com",
#  "photoURL": "https://lh3.googleusercontent.com/a-/AOh14GjiF9Gc1oGk3K13IVEdMvmYGBzChmX4t3ayGvYkgg=s96-c",
#  "displayName": "Simon Itti"
#}

###

POST http://localhost:8080/user/login
Content-Type: application/json

{
  "uid": "XNVU0NfasfW6Iyehn5nXixODyHI2",
  "email": "simon.ittensammer@gmail.com",
  "photoURL": "https://lh3.googleusercontent.com/a-/AOh14GjiF9Gc1oGk3K13IVEdMvmYGBzChmX4t3ayGvYkgg=s96-c",
  "displayName": "Simon Itti"
}

###

GET http://localhost:8080/user
Accept: application/json

###

GET http://localhost:8080/user/XNVU0NfasfW6Iyehn5nXixODyHI2

###

POST http://localhost:8080/user/XNVU0NfasfW6Iyehn5nXixODyHI2/pinboard
Content-Type: application/json

{
  "name": "Work Notes"
}

###

GET http://localhost:8080/user/XNVU0NfasfW6Iyehn5nXixODyHI2/pinboards

###

DELETE http://localhost:8080/user/XNVU0NfasfW6Iyehn5nXixODyHI2/deletePinboard/1

###
